services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "6543:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./EVENT_MANAGER/.env
    networks: [em-net]

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6380:6379"
    networks: [em-net]

  event-manager:
    build:
      context: ./EVENT_MANAGER           # ← use the service folder as context
      dockerfile: ./Dockerfile
    container_name: event-manager
    depends_on:
      - postgres
    env_file:
      - ./EVENT_MANAGER/.env
    ports:
      - "5020:5020"
    networks: [em-net]

  api-gateway:
    build:
      context: ./Apigateway              # ← use the service folder as context
      dockerfile: ./Dockerfile
    container_name: api-gateway
    depends_on:
      - event-manager
      - redis
    env_file:
      - ./EVENT_MANAGER/.env
    ports:
      - "5030:5030"
    networks: [em-net]

volumes:
  pgdata:

networks:
  em-net:
    driver: bridge

